version: '3'

networks:
  ecommerce-network:
    name: ecommerce-network

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-admin
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/ecommerce
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=pato_secret_key
      - API_BASE_URL=http://localhost:3000/api
      - CORS_ORIGIN=http://localhost:4000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - mongo
    networks:
      - ecommerce-network
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: ecommerce-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - ecommerce-network
    restart: unless-stopped

volumes:
  mongo-data:
