# Docker Compose para Panel de Administración
# Puede ejecutarse independiente o conectado con frontend

networks:
  ecommerce-network:
    name: ecommerce-network
    driver: bridge

services:
  # Panel de Administración
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-admin
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://ecommerce-mongodb-admin:27017/ecommerce
      - PORT=3000
      # Configuración S3 (opcional)
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY:-}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - mongodb
    networks:
      - ecommerce-network
    restart: unless-stopped

  # Base de datos MongoDB
  mongodb:
    image: mongo:6.0
    container_name: ecommerce-mongodb-admin
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce-network
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local
